version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: "@types/react"
      - dependency-name: "@next/bundle-analyzer"
      - dependency-name: "next"
      - dependency-name: "eslint-config-next"
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
